[package]
name = "schwoop"
version = "0.1.0"
authors = ["Daniel Wilkins <tekk@parlementum.net>"]

[dependencies]
piston = "0.24.0"
piston2d-graphics = "0.16.0"
pistoncore-glutin_window = "0.28.0"
piston2d-opengl_graphics = "0.31.0"

rand = "0.3.14"
