// Generated by js_of_ocaml 2.5
(function(b){"use strict";var
aS=125,ag=".",F=255,aR=224,af="+",C=65535,a5='"',o=16777215,D=1024,H=105,a2=-88,aj=110,a1=57343,aQ=127,S="'",ak=115,aY=-32,R="int_of_string",a4=512,q=" ",ai="e",w="-",aP="nan",e="",Q=-48,d=128,aO=56320,aZ=100,ah=" : file already exists",aV=240,a0=2048,l="0",aN="/",aX=114,a3="fd ",aT="index out of bounds";function
at(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
as(a,b,c){var
d=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return d.apply(null,a);var
f=e;for(;0<c;b+=D,c-=D)f+=d.apply(null,at(a,b,Math.min(c,D)));return f}function
T(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
v(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?as(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?as(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)T(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
cq(a,b){var
e=a.length,d=new
Array(e+1),c=0;for(;c<e;c++)d[c]=a[c];d[c]=b;return d}function
y(c,b){if(c.fun)return y(c.fun,b);var
a=c.length,d=b.length,e=a-d;if(e==0)return c.apply(null,b);else
if(e<0)return y(c.apply(null,at(b,0,a)),at(b,a,d-a));else
return function(a){return y(c,cq(b,a))}}function
ce(a,b){throw[0,a,b]}function
Z(a,b){if(b.repeat)return b.repeat(a);var
c=e,d=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;d++;if(d==9)b.slice(0,1)}}function
a8(a){if(a.t==2)a.c+=Z(a.l-a.c.length,"\0");else
a.c=as(a.c,0,a.c.length);a.t=0}function
ba(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>aQ)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
cl(a){for(var
l=e,f=e,i,h,j,b,c=0,k=a.length;c<k;c++){h=a.charCodeAt(c);if(h<d){for(var
g=c+1;g<k&&(h=a.charCodeAt(g))<d;g++);if(g-c>a4){f.substr(0,1);l+=f;f=e;l+=a.slice(c,g)}else
f+=a.slice(c,g);if(g==k)break;c=g}b=1;if(++c<k&&((j=a.charCodeAt(c))&-64)==d){i=j+(h<<6);if(h<aR){b=i-12416;if(b<d)b=1}else{b=2;if(++c<k&&((j=a.charCodeAt(c))&-64)==d){i=j+(i<<6);if(h<aV){b=i-925824;if(b<a0||b>=55295&&b<57344)b=2}else{b=3;if(++c<k&&((j=a.charCodeAt(c))&-64)==d&&h<245){b=j-63447168+(i<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;f+="\ufffd"}else
if(b>C)f+=String.fromCharCode(55232+(b>>10),aO+(b&1023));else
f+=String.fromCharCode(b);if(f.length>D){f.substr(0,1);l+=f;f=e}}return l+f}function
ck(a){switch(a.t){case
9:return a.c;default:a8(a);case
0:if(ba(a.c)){a.t=9;return a.c}a.t=8;case
8:return cl(a.c)}}function
s(a,b,c){this.t=a;this.c=b;this.l=c}s.prototype={toString:function(){return ck(this)}};function
c(a){return new
s(0,a,a.length)}function
aq(a,b){ce(a,c(b))}var
f=[0];function
I(a){aq(f[4],a)}function
bS(){I(aT)}function
a7(a,b){if(b>>>0>=a.length-1)bS();return a}function
bT(a){if(isFinite(a)){if(Math.abs(a)>=2.22507385850720138e-308)return 0;if(a!=0)return 1;return 2}return isNaN(a)?4:3}function
m(a){if(a<0)I("String.create");return new
s(a?2:9,e,a)}function
bV(a,b,c,d){if(c>0)if(b==0&&(c>=a.l||a.t==2&&c>=a.c.length))if(d==0){a.c=e;a.t=2}else{a.c=Z(c,String.fromCharCode(d));a.t=c==a.l?0:2}else{if(a.t!=4)T(a);for(c+=b;b<c;b++)a.c[b]=d}return 0}function
a6(a){if((a.t&6)!=0)a8(a);return a.c}function
ap(a){a=a6(a);var
e=a.length;if(e>31)I("format_int: format too long");var
b={justify:af,signstyle:w,filler:q,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
d=0;d<e;d++){var
c=a.charAt(d);switch(c){case"-":b.justify=w;break;case"+":case" ":b.signstyle=c;break;case"0":b.filler=l;break;case"#":b.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":b.width=0;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.width=b.width*10+c;d++}d--;break;case".":b.prec=0;d++;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.prec=b.prec*10+c;d++}d--;case"d":case"i":b.signedconv=true;case"u":b.base=10;break;case"x":b.base=16;break;case"X":b.base=16;b.uppercase=true;break;case"o":b.base=8;break;case"e":case"f":case"g":b.signedconv=true;b.conv=c;break;case"E":case"F":case"G":b.signedconv=true;b.uppercase=true;b.conv=c.toLowerCase();break}}return b}function
al(a,b){if(a.uppercase)b=b.toUpperCase();var
g=b.length;if(a.signedconv&&(a.sign<0||a.signstyle!=w))g++;if(a.alternate){if(a.base==8)g+=1;if(a.base==16)g+=2}var
d=e;if(a.justify==af&&a.filler==q)for(var
f=g;f<a.width;f++)d+=q;if(a.signedconv)if(a.sign<0)d+=w;else
if(a.signstyle!=w)d+=a.signstyle;if(a.alternate&&a.base==8)d+=l;if(a.alternate&&a.base==16)d+="0x";if(a.justify==af&&a.filler==l)for(var
f=g;f<a.width;f++)d+=l;d+=b;if(a.justify==w)for(var
f=g;f<a.width;f++)d+=q;return c(d)}function
a9(a,b){var
c,f=ap(a),e=f.prec<0?6:f.prec;if(b<0){f.sign=-1;b=-b}if(isNaN(b)){c=aP;f.filler=q}else
if(!isFinite(b)){c="inf";f.filler=q}else
switch(f.conv){case"e":var
c=b.toExponential(e),d=c.length;if(c.charAt(d-3)==ai)c=c.slice(0,d-1)+l+c.slice(d-1);break;case"f":c=b.toFixed(e);break;case"g":e=e?e:1;c=b.toExponential(e-1);var
i=c.indexOf(ai),h=+c.slice(i+1);if(h<-4||b.toFixed(0).length>e){var
d=i-1;while(c.charAt(d)==l)d--;if(c.charAt(d)==ag)d--;c=c.slice(0,d+1)+c.slice(i);d=c.length;if(c.charAt(d-3)==ai)c=c.slice(0,d-1)+l+c.slice(d-1);break}else{var
g=e;if(h<0){g-=h+1;c=b.toFixed(g)}else
while(c=b.toFixed(g),c.length>e+1)g--;if(g){var
d=c.length-1;while(c.charAt(d)==l)d--;if(c.charAt(d)==ag)d--;c=c.slice(0,d+1)}}break}return al(f,c)}function
X(a,b){if(a6(a)=="%d")return c(e+b);var
d=ap(a);if(b<0)if(d.signedconv){d.sign=-1;b=-b}else
b>>>=0;var
f=b.toString(d.base);if(d.prec>=0){d.filler=q;var
g=d.prec-f.length;if(g>0)f=Z(g,l)+f}return al(d,f)}function
bZ(a){return(a[3]|a[2]|a[1])==0}function
b2(a){return[F,a&o,a>>24&o,a>>31&C]}function
bd(a){var
d=a.length,c=new
Array(d);for(var
b=0;b<d;b++)c[b]=a[b];return c}function
b3(a,b){var
c=a[1]-b[1],d=a[2]-b[2]+(c>>24),e=a[3]-b[3]+(d>>24);return[F,c&o,d&o,e&C]}function
a$(a,b){if(a[3]>b[3])return 1;if(a[3]<b[3])return-1;if(a[2]>b[2])return 1;if(a[2]<b[2])return-1;if(a[1]>b[1])return 1;if(a[1]<b[1])return-1;return 0}function
a_(a){a[3]=a[3]<<1|a[2]>>23;a[2]=(a[2]<<1|a[1]>>23)&o;a[1]=a[1]<<1&o}function
b0(a){a[1]=(a[1]>>>1|a[2]<<23)&o;a[2]=(a[2]>>>1|a[3]<<23)&o;a[3]=a[3]>>>1}function
b5(a,b){var
e=0,d=bd(a),c=bd(b),f=[F,0,0,0];while(a$(d,c)>0){e++;a_(c)}while(e>=0){e--;a_(f);if(a$(d,c)>=0){f[1]++;d=b3(d,c)}b0(c)}return[0,f,d]}function
b4(a){return a[1]|a[2]<<24}function
bY(a){return a[3]<<16<0}function
b1(a){var
b=-a[1],c=-a[2]+(b>>24),d=-a[3]+(c>>24);return[F,b&o,c&o,d&C]}function
bX(a,b){var
c=ap(a);if(c.signedconv&&bY(b)){c.sign=-1;b=b1(b)}var
d=e,i=b2(c.base),h="0123456789abcdef";do{var
g=b5(b,i);b=g[1];d=h.charAt(b4(g[2]))+d}while(!bZ(b));if(c.prec>=0){c.filler=q;var
f=c.prec-d.length;if(f>0)d=Z(f,l)+d}return al(c,d)}function
i(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
g(a){return a.l}function
cd(a){var
b=0,d=g(a),c=10,e=d>0&&i(a,0)==45?(b++,-1):1;if(b+1<d&&i(a,b)==48)switch(i(a,b+1)){case
120:case
88:c=16;b+=2;break;case
111:case
79:c=8;b+=2;break;case
98:case
66:c=2;b+=2;break}return[b,e,c]}function
be(a){if(a>=48&&a<=57)return a-48;if(a>=65&&a<=90)return a-55;if(a>=97&&a<=122)return a-87;return-1}function
U(a){aq(f[3],a)}function
b6(a){var
j=cd(a),d=j[0],k=j[1],e=j[2],h=g(a),l=-1>>>0,f=d<h?i(a,d):0,c=be(f);if(c<0||c>=e)U(R);var
b=c;for(d++;d<h;d++){f=i(a,d);if(f==95)continue;c=be(f);if(c<0||c>=e)break;b=e*b+c;if(b>l)U(R)}if(d!=h)U(R);b=k*b;if(e==10&&(b|0)!=b)U(R);return b|0}function
an(a){return+(a>31&&a<aQ)}function
b8(a,b){var
a=a+1|0,c=new
Array(a);c[0]=0;for(var
d=1;d<a;d++)c[d]=b;return c}function
k(a){aq(f[2],a)}function
ao(a){if(!a.opened)k("Cannot flush a closed channel");if(a.buffer==e)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=e;return 0}function
r(a){this.data=a}r.prototype={truncate:function(){this.data=m(0)}};function
bf(a){a=a
instanceof
s?a.toString():a;k(a+": No such file or directory")}var
bU=aN;function
V(a){a=a
instanceof
s?a.toString():a;if(a.charCodeAt(0)!=47)a=bU+a;var
d=a.split(aN),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(e);break;default:b.push(d[c]);break}b.orig=a;return b}function
u(){this.content={}}u.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
Y=new
u();Y.mk(e,new
u());function
am(a){var
b=Y;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))bf(a.orig);b=b.get(a[c])}return b}function
cj(a){var
c=V(a),b=am(c);return b
instanceof
u?1:0}function
cg(a){return new
s(4,a,a.length)}function
cr(a){if(a.t!=4)T(a);return a.c}function
bW(a,b){var
f=V(a),d=Y;for(var
g=0;g<f.length-1;g++){var
e=f[g];if(!d.exists(e))d.mk(e,new
u());d=d.get(e);if(!(d
instanceof
u))k(f.orig+ah)}var
e=f[f.length-1];if(d.exists(e))k(f.orig+ah);if(b
instanceof
u)d.mk(e,b);else
if(b
instanceof
r)d.mk(e,b);else
if(b
instanceof
s)d.mk(e,new
r(b));else
if(b
instanceof
Array)d.mk(e,new
r(cg(b)));else
if(b.toString)d.mk(e,new
r(c(b.toString())));else
I("caml_fs_register");return 0}function
ci(a){var
b=Y,d=V(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
J(a,b,c){if(f.fds===undefined)f.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?g(b.data):0;d.flags=c;f.fds[a]=d;f.fd_last_idx=a;return a}function
cs(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
g=a.toString(),i=V(a);if(d.rdonly&&d.wronly)k(g+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)k(g+" : flags Open_text and Open_binary are not compatible");if(ci(a)){if(cj(a))k(g+" : is a directory");if(d.create&&d.excl)k(g+ah);var
h=f.fd_last_idx?f.fd_last_idx:0,e=am(i);if(d.truncate)e.truncate();return J(h+1,e,d)}else
if(d.create){var
h=f.fd_last_idx?f.fd_last_idx:0;bW(a,m(0));var
e=am(i);return J(h+1,e,d)}else
bf(a)}J(0,new
r(m(0)));J(1,new
r(m(0)));J(2,new
r(m(0)));function
b9(a){var
b=f.fds[a];if(b.flags.wronly)k(a3+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true}}function
co(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}function
cp(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}var
W=new
Array();function
cf(a,b){var
i=c(b),d=g(i),h=g(a.file.data),f=a.offset;if(f+d>=h){var
e=m(f+d);v(a.file.data,0,e,0,h);v(i,0,e,f,d);a.file.data=e}a.offset+=d;return 0}function
bb(a){var
b;switch(a){case
1:b=cp;break;case
2:b=co;break;default:b=cf}var
d=f.fds[a];if(d.flags.rdonly)k(a3+a+" is readonly");var
c={file:d.file,offset:d.offset,fd:a,opened:true,buffer:e,output:b};W[c.fd]=c;return c}function
b_(){var
a=0;for(var
b
in
W)if(W[b].opened)a=[0,W[b],a];return a}function
bc(a,b,c,d){if(!a.opened)k("Cannot output to a closed channel");var
f;if(c==0&&g(b)==d)f=b;else{f=m(d);v(b,c,f,0,d)}var
e=f.toString(),h=e.lastIndexOf("\n");if(h<0)a.buffer+=e;else{a.buffer+=e.substr(0,h+1);ao(a);a.buffer+=e.substr(h+1)}return 0}function
b$(a,b){var
d=c(String.fromCharCode(b));bc(a,d,0,1);return 0}if(!Math.imul)Math.imul=function(a,b){return((a>>16)*b<<16)+(a&C)*b|0};var
ca=Math.imul;function
a(a,b){f[a+1]=b}function
bg(){I(aT)}function
E(a,b){if(b>>>0>=a.l)bg();return i(a,b)}function
h(a,b,c){c&=F;if(a.t!=4){if(b==a.c.length){a.c+=String.fromCharCode(c);if(b+1==a.l)a.t=0;return 0}T(a)}a.c[b]=c;return 0}function
ar(a,b,c){if(b>>>0>=a.l)bg();return h(a,b,c)}function
ch(){return 32}function
cm(a){for(var
h=e,c=h,b,j,f=0,i=a.length;f<i;f++){b=a.charCodeAt(f);if(b<d){for(var
g=f+1;g<i&&(b=a.charCodeAt(g))<d;g++);if(g-f>a4){c.substr(0,1);h+=c;c=e;h+=a.slice(f,g)}else
c+=a.slice(f,g);if(g==i)break;f=g}if(b<a0){c+=String.fromCharCode(192|b>>6);c+=String.fromCharCode(d|b&63)}else
if(b<55296||b>=a1)c+=String.fromCharCode(aR|b>>12,d|b>>6&63,d|b&63);else
if(b>=56319||f+1==i||(j=a.charCodeAt(f+1))<aO||j>a1)c+="\xef\xbf\xbd";else{f++;b=(b<<10)+j-56613888;c+=String.fromCharCode(aV|b>>18,d|b>>12&63,d|b>>6&63,d|b&63)}if(c.length>D){c.substr(0,1);h+=c;c=e}}return h+c}function
b7(a){var
b=9;if(!ba(a))b=8,a=cm(a);return new
s(b,a,a.length)}var
cc={};function
cb(a){return cc[a]}function
cn(a){if(a
instanceof
Array)return a;if(b.RangeError&&a
instanceof
b.RangeError&&a.message&&a.message.match(/maximum call stack/i))return[0,f[9]];if(b.InternalError&&a
instanceof
b.InternalError&&a.message&&a.message.match(/too much recursion/i))return[0,f[9]];if(a
instanceof
b.Error)return[0,cb("jsError"),a];return[0,f[3],b7(String(a))]}function
ae(a,b){return a.length==1?a(b):y(a,[b])}function
t(a,b,c){return a.length==2?a(b,c):y(a,[b,c])}function
j(a,b,c,d){return a.length==3?a(b,c,d):y(a,[b,c,d])}var
$=[0,c("Failure")],au=[0,c("Invalid_argument")],av=[0,c("Assert_failure")],ad=c("Hi!\n");a(11,[0,c("Undefined_recursive_module")]);a(10,av);a(9,[0,c("Sys_blocked_io")]);a(8,[0,c("Stack_overflow")]);a(7,[0,c("Match_failure")]);a(6,[0,c("Not_found")]);a(5,[0,c("Division_by_zero")]);a(4,[0,c("End_of_file")]);a(3,au);a(2,$);a(1,[0,c("Sys_error")]);a(0,[0,c("Out_of_memory")]);var
bh=c("true"),bi=c("false"),bm=c("\\b"),bn=c("\\t"),bo=c("\\n"),bp=c("\\r"),bl=c("\\\\"),bk=c("\\'"),br=c("String.blit"),bq=c("String.sub"),bs=c("Buffer.add: cannot grow buffer"),bJ=c(e),bK=c(e),bN=c("%.12g"),bO=c(a5),bP=c(a5),bL=c(S),bM=c(S),bI=c(aP),bG=c("neg_infinity"),bH=c("infinity"),bF=c(ag),bE=c("printf: bad positional specification (0)."),bD=c("%_"),bC=[0,c("printf.ml"),143,8],bz=c(S),bA=c("Printf: premature end of format string '"),bv=c(S),bw=c(" in format string '"),bx=c(", at char number "),by=c("Printf: bad conversion %"),bt=c("Sformat.index_of_int: negative argument ");function
_(a){throw[0,$,a]}function
K(a){throw[0,au,a]}function
n(a,b){var
c=g(a),e=g(b),d=m(c+e|0);v(a,0,d,0,c);v(b,0,d,c,e);return d}function
aa(a){return c(e+a)}b9(0);var
A=bb(1);bb(2);function
L(a,b){var
c=m(a);bV(c,0,a,b);return c}function
M(a,b,c){if(0<=b)if(0<=c)if(!((g(a)-c|0)<b)){var
d=m(c);v(a,b,d,0,c);return d}return K(bq)}function
N(a,b,c,d,e){if(0<=e)if(0<=b)if(!((g(a)-e|0)<b))if(0<=d)if(!((g(c)-e|0)<d))return v(a,b,c,d,e);return K(br)}var
aw=ch(0),z=ca(aw/8|0,(1<<(aw-10|0))-1|0)-1|0;function
ax(a){var
b=1<=a?a:1,c=z<b?z:b,d=m(c);return[0,d,0,c,d]}function
ay(a){return M(a[1],0,a[2])}function
az(a,b){var
c=[0,a[3]];for(;;){if(c[1]<(a[2]+b|0)){c[1]=2*c[1]|0;continue}if(z<c[1])if((a[2]+b|0)<=z)c[1]=z;else
_(bs);var
d=m(c[1]);N(a[1],0,d,0,a[2]);a[1]=d;a[3]=c[1];return 0}}function
O(a,b){var
c=a[2];if(a[3]<=c)az(a,1);ar(a[1],c,b);a[2]=c+1|0;return 0}function
aA(a,b){var
c=g(b),d=a[2]+c|0;if(a[3]<d)az(a,c);N(b,0,a[1],a[2],c);a[2]=d;return 0}function
ab(a){return 0<=a?a:_(n(bt,aa(a)))}function
aB(a,b){return ab(a+b|0)}var
bu=1;function
aC(a){return aB(bu,a)}function
aD(a){return M(a,0,g(a))}function
aE(a,b,c){var
d=n(bw,n(a,bv)),e=n(bx,n(aa(b),d));return K(n(by,n(L(1,c),e)))}function
G(a,b,c){return aE(aD(a),b,c)}function
P(a){return K(n(bA,n(aD(a),bz)))}function
bB(d){function
a(a,b){var
e=a,c=b;for(;;){if(g(d)<=c)return[0,0,e];var
f=i(d,c);if(49<=f){if(!(58<=f))return[0,b6(M(d,c,(g(d)-c|0)-1|0)),e]}else
if(45===f){var
e=1,c=c+1|0;continue}var
c=c+1|0;continue}}try{var
b=a(0,1)}catch(f){f=cn(f);if(f[1]===$)return aE(d,0,ak);throw f}return b}function
x(j,b,c,d){function
k(a){if(9<(i(j,a)+Q|0)>>>0)return a;var
b=a+1|0;for(;;){var
c=i(j,b);if(48<=c){if(!(58<=c)){var
b=b+1|0;continue}}else
if(36===c)return b+1|0;return a}}var
l=k(b+1|0),f=ax((c-l|0)+10|0);O(f,37);var
e=d,h=0;for(;;){if(e){var
n=[0,e[1],h],e=e[2],h=n;continue}var
a=l,g=h;for(;;){if(a<=c){var
m=i(j,a);if(42===m){if(g){var
o=g[2];aA(f,aa(g[1]));var
a=k(a+1|0),g=o;continue}throw[0,av,bC]}O(f,m);var
a=a+1|0;continue}return ay(f)}}}function
aF(a,b,c,d,e){var
f=x(b,c,d,e);if(78!==a)if(aj!==a)return f;ar(f,g(f)-1|0,117);return f}function
aG(a){return function(d,b){var
j=g(d);function
k(a,b){var
m=40===a?41:aS,c=b;for(;;){if(j<=c)return P(d);if(37===E(d,c)){var
e=c+1|0;if(j<=e)return P(d);var
f=E(d,e),h=f-40|0;if(1<h>>>0){var
l=h-83|0;if(2<l>>>0)var
g=1;else
switch(l){case
0:var
i=0,g=0;break;case
1:var
g=1;break;default:var
i=1,g=0}if(g){var
c=e+1|0;continue}}else
var
i=0===h?0:1;if(i)return f===m?e+1|0:G(d,b,f);var
c=k(f,e+1|0)+1|0;continue}var
c=c+1|0;continue}}return k(a,b)}}function
aH(k,b,c){var
n=g(k)-1|0;function
r(a){var
m=a;a:for(;;){if(m<n){if(37===E(k,m)){var
f=0,h=m+1|0;for(;;){if(n<h)var
e=P(k);else{var
o=i(k,h);if(58<=o){if(95===o){var
f=1,h=h+1|0;continue}}else
if(32<=o)switch(o+aY|0){case
10:var
h=j(b,f,h,H);continue;case
0:case
3:case
11:case
13:var
h=h+1|0;continue;case
1:case
2:case
4:case
5:case
6:case
7:case
8:case
9:case
12:case
15:break;default:var
h=h+1|0;continue}var
d=h;b:for(;;){if(n<d)var
e=P(k);else{var
l=i(k,d);if(126<=l)var
g=0;else
switch(l){case
40:var
e=r(j(b,f,d,l)),g=1;break;case
123:var
v=j(b,f,d,l),w=t(aG(l),k,v),p=v;for(;;){if(p<(w-2|0)){var
p=t(c,p,E(k,p));continue}var
d=w-1|0;continue b}case
67:case
99:var
e=j(b,f,d,99),g=1;break;case
66:case
98:var
e=j(b,f,d,66),g=1;break;case
41:case
125:var
e=j(b,f,d,l),g=1;break;case
83:case
91:case
115:var
e=j(b,f,d,ak),g=1;break;case
97:case
114:case
116:var
e=j(b,f,d,l),g=1;break;case
76:case
108:case
110:var
s=d+1|0;if(n<s)var
e=j(b,f,d,H),g=1;else{var
u=E(k,s)+a2|0;if(32<u>>>0)var
q=1;else
switch(u){case
0:case
12:case
17:case
23:case
29:case
32:var
e=t(c,j(b,f,d,l),H),g=1,q=0;break;default:var
q=1}if(q)var
e=j(b,f,d,H),g=1}break;case
33:case
37:case
44:case
64:var
e=d+1|0,g=1;break;case
69:case
70:case
71:case
101:case
102:case
103:var
e=j(b,f,d,102),g=1;break;case
78:case
88:case
100:case
105:case
111:case
117:case
120:var
e=j(b,f,d,H),g=1;break;default:var
g=0}if(!g)var
e=G(k,d,l)}break}}var
m=e;continue a}}var
m=m+1|0;continue}return m}}r(0);return 0}function
aI(a){var
d=[0,0,0,0];function
b(a,b,c){var
f=41!==c?1:0,g=f?aS!==c?1:0:f;if(g){var
e=97===c?2:1;if(aX===c)d[3]=d[3]+1|0;if(a)d[2]=d[2]+e|0;else
d[1]=d[1]+e|0}return b+1|0}aH(a,b,function(a,b){return a+1|0});return d[1]}function
aK(a,b,c){var
g=i(a,c);if(9<(g+Q|0)>>>0)return t(b,0,c);var
e=g+Q|0,d=c+1|0;for(;;){var
f=i(a,d);if(48<=f){if(!(58<=f)){var
e=(10*e|0)+(f+Q|0)|0,d=d+1|0;continue}}else
if(36===f)return 0===e?_(bE):t(b,[0,ab(e-1|0)],d+1|0);return t(b,0,c)}}function
p(a,b){return a?b:aC(b)}function
aL(a,b){return a?a[1]:b}function
bR(a){return 0}var
aW=0;function
ac(a){return bc(A,a,0,g(a))}function
aU(a,b,j,aV){var
f=g(j);function
C(k,b){var
o=b;for(;;){if(f<=o)return ae(a,A);var
c=i(j,o);if(37===c){var
l=function(a,b){var
c=aL(a,b);return a7(aV,c)[c+1]},at=function(f,e,c,d){var
a=d;for(;;){var
au=i(j,a)+aY|0;if(!(25<au>>>0))switch(au){case
10:return aK(j,function(a,b){var
d=[0,l(a,e),c];return at(f,p(a,e),d,b)},a+1|0);case
1:case
2:case
4:case
5:case
6:case
7:case
8:case
9:case
12:case
15:break;default:var
a=a+1|0;continue}var
q=i(j,a);if(!(124<=q))switch(q){case
33:ao(A);return C(e,a+1|0);case
41:return r(e,bJ,a+1|0);case
44:return r(e,bK,a+1|0);case
70:var
aa=l(f,e);if(0===c)var
aD=bN;else{var
_=x(j,o,a,c);if(70===q)ar(_,g(_)-1|0,103);var
aD=_}var
as=bT(aa);if(3===as)var
ab=aa<0?bG:bH;else
if(4<=as)var
ab=bI;else{var
T=a9(aD,aa),S=0,a_=g(T);for(;;){if(a_<=S)var
aq=n(T,bF);else{var
$=E(T,S)-46|0,bx=23<$>>>0?55===$?1:0:21<($-1|0)>>>0?1:0;if(!bx){var
S=S+1|0;continue}var
aq=T}var
ab=aq;break}}return r(p(f,e),ab,a+1|0);case
91:return G(j,a,q);case
97:var
aQ=l(f,e),aR=aC(aL(f,e)),aS=l(0,aR),bs=a+1|0,bt=p(f,aR);if(aW)ac(t(aQ,0,aS));else
t(aQ,A,aS);return C(bt,bs);case
114:return G(j,a,q);case
116:var
aT=l(f,e),bu=a+1|0,bv=p(f,e);if(aW)ac(ae(aT,0));else
ae(aT,A);return C(bv,bu);case
37:case
64:return r(e,L(1,q),a+1|0);case
83:case
115:var
y=l(f,e);if(ak===q)var
z=y;else{var
b=[0,0],ai=g(y)-1|0,a0=0;if(!(ai<0)){var
K=a0;for(;;){var
w=i(y,K),by=14<=w?34===w?1:92===w?1:0:11<=w?13<=w?1:0:8<=w?1:0,a4=by?2:an(w)?1:4;b[1]=b[1]+a4|0;var
a5=K+1|0;if(ai!==K){var
K=a5;continue}break}}if(b[1]===g(y))var
aP=y;else{var
k=m(b[1]);b[1]=0;var
al=g(y)-1|0,a1=0;if(!(al<0)){var
I=a1;for(;;){var
v=i(y,I),J=v-34|0;if(58<J>>>0)if(-20<=J)var
W=1;else{switch(J+34|0){case
8:h(k,b[1],92);b[1]++;h(k,b[1],98);var
H=1;break;case
9:h(k,b[1],92);b[1]++;h(k,b[1],116);var
H=1;break;case
10:h(k,b[1],92);b[1]++;h(k,b[1],aj);var
H=1;break;case
13:h(k,b[1],92);b[1]++;h(k,b[1],aX);var
H=1;break;default:var
W=1,H=0}if(H)var
W=0}else
var
W=56<(J-1|0)>>>0?(h(k,b[1],92),b[1]++,h(k,b[1],v),0):1;if(W)if(an(v))h(k,b[1],v);else{h(k,b[1],92);b[1]++;h(k,b[1],48+(v/aZ|0)|0);b[1]++;h(k,b[1],48+((v/10|0)%10|0)|0);b[1]++;h(k,b[1],48+(v%10|0)|0)}b[1]++;var
a3=I+1|0;if(al!==I){var
I=a3;continue}break}}var
aP=k}var
z=n(bP,n(aP,bO))}if(a===(o+1|0))var
aO=z;else{var
am=bB(x(j,o,a,c)),P=am[1],B=g(z),a6=am[2],Q=0,a7=32;if(P===B)if(0===Q)var
Z=z,ad=1;else
var
ad=0;else
var
ad=0;if(!ad)if(P<=B)var
Z=M(z,Q,B);else{var
Y=L(P,a7);if(a6)N(z,Q,Y,0,B);else
N(z,Q,Y,P-B|0,B);var
Z=Y}var
aO=Z}return r(p(f,e),aO,a+1|0);case
67:case
99:var
s=l(f,e);if(99===q)var
az=L(1,s);else{if(39===s)var
u=bk;else
if(92===s)var
u=bl;else{if(14<=s)var
D=0;else
switch(s){case
8:var
u=bm,D=1;break;case
9:var
u=bn,D=1;break;case
10:var
u=bo,D=1;break;case
13:var
u=bp,D=1;break;default:var
D=0}if(!D)if(an(s)){var
ah=m(1);h(ah,0,s);var
u=ah}else{var
F=m(4);h(F,0,92);h(F,1,48+(s/aZ|0)|0);h(F,2,48+((s/10|0)%10|0)|0);h(F,3,48+(s%10|0)|0);var
u=F}}var
az=n(bM,n(u,bL))}return r(p(f,e),az,a+1|0);case
66:case
98:var
a$=a+1|0,ba=l(f,e)?bh:bi;return r(p(f,e),ba,a$);case
40:case
123:var
U=l(f,e),av=t(aG(q),j,a+1|0);if(123===q){var
R=ax(g(U)),ap=function(a,b){O(R,b);return a+1|0};aH(U,function(a,b,c){if(a)aA(R,bD);else
O(R,37);return ap(b,c)},ap);var
a8=ay(R);return r(p(f,e),a8,av)}var
aw=p(f,e),bw=aB(aI(U),aw);return aU(function(a){return C(bw,av)},aw,U,aV);case
76:case
108:case
110:var
aE=i(j,a+1|0)+a2|0;if(!(32<aE>>>0))switch(aE){case
0:case
12:case
17:case
23:case
29:case
32:var
V=a+1|0,aJ=q-108|0;if(2<aJ>>>0)var
af=0;else{switch(aJ){case
0:var
bg=l(f,e),aN=X(x(j,o,V,c),bg),ag=1;break;case
1:var
af=0,ag=0;break;default:var
bj=l(f,e),aN=X(x(j,o,V,c),bj),ag=1}if(ag)var
aM=aN,af=1}if(!af)var
bf=l(f,e),aM=bX(x(j,o,V,c),bf);return r(p(f,e),aM,V+1|0)}var
bd=l(f,e),be=X(aF(aj,j,o,a,c),bd);return r(p(f,e),be,a+1|0);case
69:case
71:case
101:case
102:case
103:var
bb=l(f,e),bc=a9(x(j,o,a,c),bb);return r(p(f,e),bc,a+1|0);case
78:case
88:case
100:case
105:case
111:case
117:case
120:var
bq=l(f,e),br=X(aF(q,j,o,a,c),bq);return r(p(f,e),br,a+1|0)}return G(j,a,q)}},d=o+1|0,e=0;return aK(j,function(a,b){return at(a,k,e,b)},d)}b$(A,c);var
o=o+1|0;continue}}function
r(a,b,c){ac(b);return C(a,c)}return C(b,0)}var
bQ=ab(0);function
aM(a,b){return aU(bR,bQ,a,b)}var
B=aI(ad);if(6<B>>>0){var
aJ=function(f,b){if(B<=f){var
g=b8(B,0),h=function(a,b){var
c=(B-a|0)-1|0;return a7(g,c)[c+1]=b},c=0,a=b;for(;;){if(a){var
d=a[2],e=a[1];if(d){h(c,e);var
c=c+1|0,a=d;continue}h(c,e)}return aM(ad,g)}}return function(a){return aJ(f+1|0,[0,a,b])}};aJ(0,0)}else
switch(B){case
0:aM(ad,[0]);break;case
1:break;case
2:break;case
3:break;case
4:break;case
5:break}function
bj(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{ao(d)}catch(f){}var
b=c;continue}return 0}}bj(b_(0));return}(function(){return this}()));
